### ISSUE TITLE
Clearsigning with kbpgp

### ISSUE THREAD

**Issue by iamtedko** [keybase/kbpgp#109]
Hi,

Looking through the documentation, I didn't see anything that would you clearsign a message.  However, I know that it works on the command-line client.  Would it be possible to provide some more information about that?

Thanks!

**Comment by malgorithms** [comment]
hi @iamtedko  - in our email chat you mentioned hitting an error with some sample code. Can you post your attempt and the error?

**Comment by iamtedko** [comment]
Here's the error I keep getting:  

/node_modules/kbpgp/lib/openpgp/clearsign.js:168
        unhashed_subpackets: [new Issuer(this.signing_key.get_key_id())]
                                                          ^

TypeError: this.signing_key.get_key_id is not a function
    at ClearSigner._sign_msg
(/node_modules/kbpgp/lib/openpgp/clearsign.js:168:59)
    at iced.Deferrals.parent 
(/node_modules/kbpgp/lib/openpgp/clearsign.js:233:19)
    at /node_modules/kbpgp/lib/openpgp/clearsign.js:242:13
    at Deferrals.exports.Deferrals.Deferrals._call 
(/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline 
(/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill 
(/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:96:16)
    at iced.Deferrals.parent 
(/node_modules/kbpgp/lib/openpgp/clearsign.js:223:28)
    at ClearSigner.run 
(/node_modules/kbpgp/lib/openpgp/clearsign.js:225:15)
    at /node_modules/kbpgp/lib/openpgp/clearsign.js:449:11


Is this caused by passing in a wrong "signing_key" object?

**Comment by malgorithms** [comment]
hey @iamtedko - thanks for posting. I think this'll require a response from @maxtaco but I know he's on vacation this week... so I'd expect next week before he can reply. For what it's worth, I tried too and got the same error, so I think we're just doing it wrong.

Based on the previously closed issue ( https://github.com/keybase/kbpgp/issues/32 ) I thought this code would work (coffeescript):

```coffeescript
kbpgp = require 'kbpgp'

F = kbpgp.const.openpgp

opts =
  userid:        "User McTester (Born 1979) <user@example.com>"
  primary:
    nbits:       1024 # for testing...
    flags:       F.certify_keys | F.sign_data | F.auth | F.encrypt_comm | F.encrypt_storage
    expire_in:   0 # never expire
  subkeys: [
    {
      nbits:     1024
      flags:     F.sign_data
      expire_in: 86400 * 365 * 8 # 8 years
    }
    {
      nbits:     1024
      flags:     F.encrypt_comm | F.encrypt_storage
      expire_in: 86400 * 365 * 2
    }
  ]

kbpgp.KeyManager.generate opts, (err, alice) ->
  # and sign alice's subkeys
  if (not err) then alice.sign {}, (err) ->
    console.log "Made a nice test key for alice..."
    kbpgp.clearsign { msg : "hi", signing_key: alice }, (err, msg) ->
      console.log err, msg
```

**Comment by malgorithms** [comment]
Ok, I wouldn't trust this without @maxtaco 's seal of approval, but poking into the code, I think this is what you want:

```coffeescript
kbpgp.KeyManager.generate opts, (err, alice) ->
  # and sign alice's subkeys
  if (not err) then alice.sign {}, (err) ->
    console.log "Made a nice test key for alice..."

    # figure out which of her keys is best for signing!
    # clearsign doesn't do this automatically.

    flags = F.key_flags.sign_data
    signing_key = alice.find_best_pgp_key(flags)
    kbpgp.clearsign { msg : "hi", signing_key}, (err, msg) ->
      console.log msg
```

with other kbpgp operations this step is done automatically with the keymanager, but that hasn't been implemented for clearsigning yet.

**Comment by trogau** [comment]
@malgorithms, just checking to see if I'm reading your last comment correctly: do you mean that eventually there'll be a box method created to do clearsigning (similar to how signing works now)?

**Comment by poluxus** [comment]
Hi.
I would like to know if there is any improvement on the subject?
It's hard to find information about kbpgp and clearsign

**Comment by securityvoid** [comment]
I've got something which appears to be running and is identified as a signature, GPG is telling me its an invalid signature:

```
module.exports.signData = function(data, privKey, passphrase){
    "use strict";
    var deferred = q.defer();

    getKey(privKey, passphrase).then(function(key) {
        var params = {
            msg: data,
            signing_key: key.find_signing_pgp_key()
        };

        kbpgp.clearsign(params, function (err, msg) {
            if (err) {
                deferred.reject(err);
            } else {
                var signature = msg.substring(msg.indexOf('-----BEGIN PGP SIGNATURE-----'));
                deferred.resolve(signature);
            }

        });
    });
    return deferred.promise;
}

function getKey(privKey, passphrase){
    "use strict";
    var deferred = q.defer();
    kbpgp.KeyManager.import_from_armored_pgp({
        armored: privKey
    }, function(error, key) {
        if(error)
            deferred.reject(error);
        else {
            if (key.is_pgp_locked()) {
                key.unlock_pgp({
                    passphrase: passphrase
                }, function(err) {
                    if(err)
                        deferred.reject(err)
                    else
                        deferred.resolve(key);
                });
            } else
                deferred.resolve(key);
        }
    });
    return deferred.promise;
}
```

Double-checking my work now to make sure I didn't somehow miss something.

**Comment by securityvoid** [comment]
Anybody see where I messed something up?

**Comment by securityvoid** [comment]
Okay, I figured it out. The real file has a line-feed at the end-of-the-document. However, the signed version is cutting off that line-feed. As a result if you actually compare the signature against the original file read in, it doesn't match.

@maxtaco Is this a bug, or is this the way OpenPGP is designed to work? Seems like a bug. When I take a look at what is read in from the file, it has the line-feed in the string that is sent to be signed.

**Comment by securityvoid** [comment]
If I remove the last line-feed from the original file and then compare it with gpg, it then validates.
