### ISSUE TITLE
No valid primary key self-signature

### ISSUE THREAD

**Issue by jzila** [keybase/kbpgp#76]
I'm getting a failure to handle a self-signed ECC key, whereas the RSA one works perfectly.

```
no valid primary key self-signature
    at KeyBlock._check_primary (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/processor.js:85:57)
    at KeyBlock._check_keys (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/processor.js:80:19)
    at /home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/processor.js:139:25
    at Deferrals.exports.Deferrals.Deferrals._call (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/node_modules/iced-runtime/lib/runtime.js:96:16)
    at _ref1 (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/processor.js:129:32)
    at _ref1 (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/processor.js:130:15)
    at KeyBlock.process (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/processor.js:135:15)
    at warnings (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/keymanager.js:1315:18)
    at KeyManager.primary (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/keymanager.js:1324:15)
    at Function.KeyManager.import_from_pgp_message (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/keymanager.js:1331:15)
    at iced.Deferrals.parent (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/keymanager.js:1058:26)
    at iced.Deferrals.parent (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/keymanager.js:1073:15)
    at Function.KeyManager.import_from_armored_pgp (/home/john/repos/kb-login-ext/node_modules/kb-signin/node_modules/kbpgp/lib/openpgp/keymanager.js:1078:15)
```

Keypair generation code (without `ecc: true` it works perfectly):
```JavaScript
    var opts = {
        userid: "Keybase Login Extension",
        primary: {
            nbits:     384,
            ecc:       true,
            flags:     F.certify_keys | F.sign_data | F.auth | F.encrypt_comm | F.encrypt_storage,
            expire_in: 60 * 15
        },
        subkeys: [{
            nbits:     384,
            flags:     F.sign_data,
            expire_in: 60 * 15
        }]
    };
```

**Comment by maxtaco** [comment]
Can you provide more context?  I.e., a self-contained snippet to reproduce the issue? Thanks.

**Comment by jzila** [comment]
https://github.com/jzila/keybase-bug-demo

**Comment by maxtaco** [comment]
Afk for a bit. Does it work btw to call generate_gcc rather than generate?

**Comment by jzila** [comment]
Yep it does, but then I can't set the expiry.

**Comment by maxtaco** [comment]
Just for now I would copy the args used in generate_ecc and add the desired
expiration.

**Comment by jzila** [comment]
Sweet, that worked. Thanks :).

**Comment by maxtaco** [comment]
Great. It is likely an unexpected combination of options in your previous
code.

**Comment by jzila** [comment]
I used the options from here: https://keybase.io/kbpgp/docs/generating_a_pair, so maybe the docs should be updated?

**Comment by maxtaco** [comment]
DEfinitely.  Thanks for those details.
